### ISSUE TITLE
program errors on empty YAML sections

### ISSUE THREAD

**Issue by borismw** [mogensen/kubernetes-split-yaml#8]
Hey, first of all: Thanks for this very useful tool!

I sometimes use kubernetes-split-yaml in conjunction with `helm template`. In certain cases this gives YAML files with empty comment sections, for instance

```
[...]
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []

---
# Source: crds/platform.confluent.io_zookeepers.yaml - this empty section here causes an error

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
[...]
```

This causes `kubernetes-split-yaml` to error with
> WARN[0000] Ignoring yaml file with kind missing         
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x5c3c1a]
> 
> goroutine 1 [running]:
> main.outFile(0x620806, 0x9, 0xc00002c740, 0xc00014fd68, 0x0, 0x1, 0x1, 0xc00014fcb8, 0x40e4fb)
>         /home/lalala/go/pkg/mod/github.com/mogensen/kubernetes-split-yaml@v0.3.0/main.go:107 +0x3a
> main.handleFile(0xc00002c700, 0x7ffe162ebe0b, 0x1d)
>         /home/lalala/go/pkg/mod/github.com/mogensen/kubernetes-split-yaml@v0.3.0/main.go:181 +0x412
> main.main.func1(0xc00002c700, 0x7ffe162ebe0b, 0x1d)
>        /home/lalala/go/pkg/mod/github.com/mogensen/kubernetes-split-yaml@v0.3.0/main.go:94 +0x8f
> github.com/urfave/cli/v2.(*App).RunContext(0xc000001980, 0x664518, 0xc0000260e0, 0xc000012040, 0x2, 0x2, 0x0, 0x0)
>        /home/lalala/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:315 +0x6fe
> github.com/urfave/cli/v2.(*App).Run(...)
>        /home/lalala/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
> main.main()
>         /home/lalala/go/pkg/mod/github.com/mogensen/kubernetes-split-yaml@v0.3.0/main.go:98 +0xf3

However, if you remove those empty sections, splitting is possible again.

Actual behavior: Program errors on empty YAML sections
Expected behavior: Program ignores empty YAML sections
